In [1]:
%%timeit -r 10 -n 30

from sqlalchemy import create_engine, Column, Integer, String, DateTime, ForeignKey
from sqlalchemy.orm import declarative_base, relationship, sessionmaker
from datetime import datetime

Base = declarative_base()

# Definizione delle classi delle tabelle
class ProdottiOrdinati(Base):
    __tablename__ = 'ProdottiOrdinati'

    ID = Column(Integer, primary_key=True)
    NumeroOrdine = Column(Integer, ForeignKey('OrdiniClienti.NumeroOrdine'))
    NomeModello = Column(String)
    Quantita = Column(Integer)
    PrezzoUnitario = Column(Integer)
    Valuta = Column(String)
    DataAggiunta = Column(DateTime)
    DataConsegnaPrevista = Column(DateTime)
    StatoProdotto = Column(String)
    NumeroRMA = Column(Integer)
    Note = Column(String)
    # Altre colonne...

class ApparecchiatureElettroniche(Base):
    __tablename__ = 'ApparecchiatureElettroniche'

    NomeModello = Column(String, primary_key=True)
    NumeroSerie = Column(Integer)
    DataProduzione = Column(DateTime)
    Reparto = Column(String)
    Fornitore = Column(String)
    DataAcquisto = Column(DateTime)
    Cliente = Column(String)
    RepartoAssistenza = Column(String)
    DataUltimaManutenzione = Column(DateTime)
    GaranziaScadenza = Column(DateTime)
    DescrizioneProblema = Column(String)
    ComponenteDifettoso = Column(String)
    TecnicoAssistenza = Column(String)
    Note = Column(String)
    # Altre colonne...

class OrdiniClienti(Base):
    __tablename__ = 'OrdiniClienti'

    NumeroOrdine = Column(Integer, primary_key=True)
    DataOrdine = Column(DateTime)
    Cliente = Column(String)
    IndirizzoSpedizione = Column(String)
    CittaSpedizione = Column(String)
    CAPSpedizione = Column(String)
    ProvinciaSpedizione = Column(String)
    NazioneSpedizione = Column(String)
    MetodoPagamento = Column(String)
    StatoPagamento = Column(String)
    DataPagamento = Column(DateTime)
    MetodoSpedizione = Column(String)
    DataSpedizione = Column(DateTime)
    StatoSpedizione = Column(String)
    DataConsegna = Column(DateTime)
    TotaleOrdine = Column(Integer)
    Valuta = Column(String)
    NumeroFattura = Column(Integer)
    CodicePromozionale = Column(String)
    Note = Column(String)
    # Altre colonne...

# Configurazione del motore di database
engine = create_engine('mysql://root:oirad1993@localhost/database4test', echo=True)  # Sostituisci con le tue credenziali

# Creazione delle tabelle nel database
Base.metadata.create_all(engine)

# Creazione di una sessione SQLAlchemy
Session = sessionmaker(bind=engine)
session = Session()

# Costruzione della query
query = (
    session.query(
        ProdottiOrdinati.ID.label('ProdottoOrdinatoID'),
        ProdottiOrdinati.NumeroOrdine,
        ProdottiOrdinati.NomeModello,
        ProdottiOrdinati.Quantita,
        ProdottiOrdinati.PrezzoUnitario.label('PrezzoUnitarioProdotto'),
        ProdottiOrdinati.Valuta.label('ValutaProdotto'),
        ProdottiOrdinati.DataAggiunta,
        ProdottiOrdinati.DataConsegnaPrevista,
        ProdottiOrdinati.StatoProdotto,
        ProdottiOrdinati.NumeroRMA,
        ProdottiOrdinati.Note.label('NoteProdotto'),
        ApparecchiatureElettroniche.NomeModello.label('NomeModelloApparecchiatura'),
        ApparecchiatureElettroniche.NumeroSerie,
        ApparecchiatureElettroniche.DataProduzione,
        ApparecchiatureElettroniche.Reparto,
        ApparecchiatureElettroniche.Fornitore.label('FornitoreApparecchiatura'),
        ApparecchiatureElettroniche.DataAcquisto,
        ApparecchiatureElettroniche.Cliente,
        ApparecchiatureElettroniche.RepartoAssistenza,
        ApparecchiatureElettroniche.DataUltimaManutenzione,
        ApparecchiatureElettroniche.GaranziaScadenza,
        ApparecchiatureElettroniche.DescrizioneProblema,
        ApparecchiatureElettroniche.ComponenteDifettoso,
        ApparecchiatureElettroniche.TecnicoAssistenza,
        ApparecchiatureElettroniche.Note.label('NoteApparecchiatura'),
        OrdiniClienti.NumeroOrdine.label('NumeroOrdineCliente'),
        OrdiniClienti.DataOrdine,
        OrdiniClienti.Cliente.label('ClienteOrdine'),
        OrdiniClienti.IndirizzoSpedizione,
        OrdiniClienti.CittaSpedizione,
        OrdiniClienti.CAPSpedizione,
        OrdiniClienti.ProvinciaSpedizione,
        OrdiniClienti.NazioneSpedizione,
        OrdiniClienti.MetodoPagamento,
        OrdiniClienti.StatoPagamento,
        OrdiniClienti.DataPagamento,
        OrdiniClienti.MetodoSpedizione,
        OrdiniClienti.DataSpedizione,
        OrdiniClienti.StatoSpedizione,
        OrdiniClienti.DataConsegna,
        OrdiniClienti.TotaleOrdine,
        OrdiniClienti.Valuta.label('ValutaOrdine'),
        OrdiniClienti.NumeroFattura,
        OrdiniClienti.CodicePromozionale,
        OrdiniClienti.Note.label('NoteOrdine')
    )
    .join(ApparecchiatureElettroniche, ProdottiOrdinati.NomeModello == ApparecchiatureElettroniche.NomeModello)
    .join(OrdiniClienti, ProdottiOrdinati.NumeroOrdine == OrdiniClienti.NumeroOrdine)
    .filter(
        ProdottiOrdinati.DataAggiunta.between('2022-01-01', '2023-06-30'),
        ApparecchiatureElettroniche.DataProduzione <= '2023-06-30',
        OrdiniClienti.DataOrdine >= '2022-01-01'
    )
)

# Esecuzione della query e ottenere i risultati
results = query.all()

# Stampa dei risultati
for result in results:
    print(result)

# Chiusura della sessione
session.close()

2023-11-13 16:07:20,432 INFO sqlalchemy.engine.Engine SELECT DATABASE()
2023-11-13 16:07:20,432 INFO sqlalchemy.engine.Engine [raw sql] ()
2023-11-13 16:07:20,432 INFO sqlalchemy.engine.Engine SELECT @@sql_mode
2023-11-13 16:07:20,432 INFO sqlalchemy.engine.Engine [raw sql] ()
2023-11-13 16:07:20,445 INFO sqlalchemy.engine.Engine SELECT @@lower_case_table_names
2023-11-13 16:07:20,446 INFO sqlalchemy.engine.Engine [raw sql] ()
2023-11-13 16:07:20,448 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-11-13 16:07:20,448 INFO sqlalchemy.engine.Engine DESCRIBE `database4test`.`ProdottiOrdinati`
2023-11-13 16:07:20,448 INFO sqlalchemy.engine.Engine [raw sql] ()
2023-11-13 16:07:20,448 INFO sqlalchemy.engine.Engine DESCRIBE `database4test`.`ApparecchiatureElettroniche`
2023-11-13 16:07:20,448 INFO sqlalchemy.engine.Engine [raw sql] ()
2023-11-13 16:07:20,461 INFO sqlalchemy.engine.Engine DESCRIBE `database4test`.`OrdiniClienti`
2023-11-13 16:07:20,462 INFO sqlalchemy.engine.Engine [raw sql] ()
2023-11-13 16:07:20,463 INFO sqlalchemy.engine.Engine COMMIT
2023-11-13 16:07:20,471 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-11-13 16:07:20,487 INFO sqlalchemy.engine.Engine SELECT `ProdottiOrdinati`.`ID` AS `ProdottoOrdinatoID`, `ProdottiOrdinati`.`NumeroOrdine` AS `ProdottiOrdinati_NumeroOrdine`, `ProdottiOrdinati`.`NomeModello` AS `ProdottiOrdinati_NomeModello`, `ProdottiOrdinati`.`Quantita` AS `ProdottiOrdinati_Quantita`, `ProdottiOrdinati`.`PrezzoUnitario` AS `PrezzoUnitarioProdotto`, `ProdottiOrdinati`.`Valuta` AS `ValutaProdotto`, `ProdottiOrdinati`.`DataAggiunta` AS `ProdottiOrdinati_DataAggiunta`, `ProdottiOrdinati`.`DataConsegnaPrevista` AS `ProdottiOrdinati_DataConsegnaPrevista`, `ProdottiOrdinati`.`StatoProdotto` AS `ProdottiOrdinati_StatoProdotto`, `ProdottiOrdinati`.`NumeroRMA` AS `ProdottiOrdinati_NumeroRMA`, `ProdottiOrdinati`.`Note` AS `NoteProdotto`, `ApparecchiatureElettroniche`.`NomeModello` AS `NomeModelloApparecchiatura`, `ApparecchiatureElettroniche`.`NumeroSerie` AS `ApparecchiatureElettroniche_NumeroSerie`, `ApparecchiatureElettroniche`.`DataProduzione` AS `ApparecchiatureElettroniche_DataProduzione`, `ApparecchiatureElettroniche`.`Reparto` AS `ApparecchiatureElettroniche_Reparto`, `ApparecchiatureElettroniche`.`Fornitore` AS `FornitoreApparecchiatura`, `ApparecchiatureElettroniche`.`DataAcquisto` AS `ApparecchiatureElettroniche_DataAcquisto`, `ApparecchiatureElettroniche`.`Cliente` AS `ApparecchiatureElettroniche_Cliente`, `ApparecchiatureElettroniche`.`RepartoAssistenza` AS `ApparecchiatureElettroniche_RepartoAssistenza`, `ApparecchiatureElettroniche`.`DataUltimaManutenzione` AS `ApparecchiatureElettroniche_DataUltimaManutenzione`, `ApparecchiatureElettroniche`.`GaranziaScadenza` AS `ApparecchiatureElettroniche_GaranziaScadenza`, `ApparecchiatureElettroniche`.`DescrizioneProblema` AS `ApparecchiatureElettroniche_DescrizioneProblema`, `ApparecchiatureElettroniche`.`ComponenteDifettoso` AS `ApparecchiatureElettroniche_ComponenteDifettoso`, `ApparecchiatureElettroniche`.`TecnicoAssistenza` AS `ApparecchiatureElettroniche_TecnicoAssistenza`, `ApparecchiatureElettroniche`.`Note` AS `NoteApparecchiatura`, `OrdiniClienti`.`NumeroOrdine` AS `NumeroOrdineCliente`, `OrdiniClienti`.`DataOrdine` AS `OrdiniClienti_DataOrdine`, `OrdiniClienti`.`Cliente` AS `ClienteOrdine`, `OrdiniClienti`.`IndirizzoSpedizione` AS `OrdiniClienti_IndirizzoSpedizione`, `OrdiniClienti`.`CittaSpedizione` AS `OrdiniClienti_CittaSpedizione`, `OrdiniClienti`.`CAPSpedizione` AS `OrdiniClienti_CAPSpedizione`, `OrdiniClienti`.`ProvinciaSpedizione` AS `OrdiniClienti_ProvinciaSpedizione`, `OrdiniClienti`.`NazioneSpedizione` AS `OrdiniClienti_NazioneSpedizione`, `OrdiniClienti`.`MetodoPagamento` AS `OrdiniClienti_MetodoPagamento`, `OrdiniClienti`.`StatoPagamento` AS `OrdiniClienti_StatoPagamento`, `OrdiniClienti`.`DataPagamento` AS `OrdiniClienti_DataPagamento`, `OrdiniClienti`.`MetodoSpedizione` AS `OrdiniClienti_MetodoSpedizione`, `OrdiniClienti`.`DataSpedizione` AS `OrdiniClienti_DataSpedizione`, `OrdiniClienti`.`StatoSpedizione` AS `OrdiniClienti_StatoSpedizione`, `OrdiniClienti`.`DataConsegna` AS `OrdiniClienti_DataConsegna`, `OrdiniClienti`.`TotaleOrdine` AS `OrdiniClienti_TotaleOrdine`, `OrdiniClienti`.`Valuta` AS `ValutaOrdine`, `OrdiniClienti`.`NumeroFattura` AS `OrdiniClienti_NumeroFattura`, `OrdiniClienti`.`CodicePromozionale` AS `OrdiniClienti_CodicePromozionale`, `OrdiniClienti`.`Note` AS `NoteOrdine`
FROM `ProdottiOrdinati` INNER JOIN `ApparecchiatureElettroniche` ON `ProdottiOrdinati`.`NomeModello` = `ApparecchiatureElettroniche`.`NomeModello` INNER JOIN `OrdiniClienti` ON `ProdottiOrdinati`.`NumeroOrdine` = `OrdiniClienti`.`NumeroOrdine`
WHERE `ProdottiOrdinati`.`DataAggiunta` BETWEEN %s AND %s AND `ApparecchiatureElettroniche`.`DataProduzione` <= %s AND `OrdiniClienti`.`DataOrdine` >= %s
2023-11-13 16:07:20,487 INFO sqlalchemy.engine.Engine [generated in 0.00109s] ('2022-01-01', '2023-06-30', '2023-06-30', '2022-01-01')
(15, 19, 'popular', 2, Decimal('636.16'), 'EUR', datetime.date(2022, 5, 5), datetime.date(2022, 12, 9), 'In attesa di spedizione', 'RMA9114', 'Situation once treatment fact. Game big stage never turn every never. Person man another control picture industry professional. Realize effect dark.\nRelationship floor join past skin you cold.', 'popular', 'SN029', datetime.date(2016, 9, 29), 'government', 'Jensen LLC', datetime.date(2020, 10, 2), 'Nguyen PLC', 'school', datetime.date(2021, 3, 18), datetime.date(2022, 12, 2), 'Population apply create speak determine entire. Very now foot hard information material suggest.\nMission scientist knowledge total. Organization individual early.', 'tonight', 'Kevin Stewart', 'Agency operation wide ball. Late something cause door something. Various score final expect full.\nStructure national deep specific network. Old make under free military fish top item.', 19, datetime.date(2022, 2, 28), 'Guerrero and Sons', '4127 Perry Neck\nEast Andrew, HI 81161', 'South Garyfurt', '46406', 'AL', 'Guinea-Bissau', 'Bonifico bancario', 'Completato', datetime.date(2022, 9, 15), 'Posta prioritaria', datetime.date(2022, 12, 25), 'In preparazione', datetime.date(2022, 12, 28), Decimal('651.26'), 'EUR', 'INV9006', 'PROMO5', 'Send boy wide figure use still. Determine film position never. Market within several ok.')
(17, 38, 'anyone', 4, Decimal('178.20'), 'EUR', datetime.date(2022, 1, 9), datetime.date(2022, 11, 29), 'Spedito', 'RMA5567', 'Stage impact reality nature she. Listen seek guy most. Address so including each high.\nDefense certainly five citizen get resource economy.', 'anyone', 'SN021', datetime.date(2021, 6, 3), 'his', 'Fitzgerald, Kelly and Larson', datetime.date(2022, 10, 24), 'Douglas, Smith and Mack', 'increase', datetime.date(2022, 12, 1), datetime.date(2022, 12, 24), 'Scene success throughout chance recent. Half about phone respond really two make. Change former worry thought leg.', 'Democrat', 'Rebecca Rodriguez', 'Until yourself forward room. Product issue avoid. Design morning anything four beyond.\nTogether civil daughter partner name. Task American across. Nation herself fish finish.', 38, datetime.date(2022, 5, 24), 'Wilson Ltd', '400 Joe Mountain\nMccannmouth, CT 71721', 'Jacobsonmouth', '05082', 'MO', 'Armenia', 'Bonifico bancario', 'Completato', datetime.date(2022, 9, 8), 'Corriere espresso', datetime.date(2022, 12, 15), 'In preparazione', datetime.date(2022, 12, 23), Decimal('971.59'), 'USD', 'INV2474', 'PROMO5', 'Arrive trouble city little western party. Fish sort culture skin travel democratic. Red defense down difference issue. Dark admit eight friend best.')
(17, 38, 'anyone', 4, Decimal('178.20'), 'EUR', datetime.date(2022, 1, 9), datetime.date(2022, 11, 29), 'Spedito', 'RMA5567', 'Stage impact reality nature she. Listen seek guy most. Address so including each high.\nDefense certainly five citizen get resource economy.', 'anyone', 'SN035', datetime.date(2019, 7, 16), 'despite', 'Smith Group', datetime.date(2022, 1, 17), 'Ramirez-Jones', 'popular', datetime.date(2022, 7, 15), datetime.date(2022, 9, 28), 'Begin approach she increase station level. Machine list baby traditional term. Again white thing suggest it commercial.', 'follow', 'Julia Lopez', 'Without back view staff foot worker return. Operation population action memory role single determine.', 38, datetime.date(2022, 5, 24), 'Wilson Ltd', '400 Joe Mountain\nMccannmouth, CT 71721', 'Jacobsonmouth', '05082', 'MO', 'Armenia', 'Bonifico bancario', 'Completato', datetime.date(2022, 9, 8), 'Corriere espresso', datetime.date(2022, 12, 15), 'In preparazione', datetime.date(2022, 12, 23), Decimal('971.59'), 'USD', 'INV2474', 'PROMO5', 'Arrive trouble city little western party. Fish sort culture skin travel democratic. Red defense down difference issue. Dark admit eight friend best.')
2023-11-13 16:07:20,493 INFO sqlalchemy.engine.Engine ROLLBACK
2023-11-13 16:07:20,497 INFO sqlalchemy.engine.Engine SELECT DATABASE()
2023-11-13 16:07:20,497 INFO sqlalchemy.engine.Engine [raw sql] ()
2023-11-13 16:07:20,497 INFO sqlalchemy.engine.Engine SELECT @@sql_mode
2023-11-13 16:07:20,509 INFO sqlalchemy.engine.Engine [raw sql] ()
2023-11-13 16:07:20,509 INFO sqlalchemy.engine.Engine SELECT @@lower_case_table_names
2023-11-13 16:07:20,509 INFO sqlalchemy.engine.Engine [raw sql] ()
2023-11-13 16:07:20,513 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-11-13 16:07:20,513 INFO sqlalchemy.engine.Engine DESCRIBE `database4test`.`ProdottiOrdinati`
2023-11-13 16:07:20,513 INFO sqlalchemy.engine.Engine [raw sql] ()
2023-11-13 16:07:20,518 INFO sqlalchemy.engine.Engine DESCRIBE `database4test`.`ApparecchiatureElettroniche`
2023-11-13 16:07:20,520 INFO sqlalchemy.engine.Engine [raw sql] ()
2023-11-13 16:07:20,520 INFO sqlalchemy.engine.Engine DESCRIBE `database4test`.`OrdiniClienti`
2023-11-13 16:07:20,520 INFO sqlalchemy.engine.Engine [raw sql] ()
2023-11-13 16:07:20,520 INFO sqlalchemy.engine.Engine COMMIT
2023-11-13 16:07:20,530 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-11-13 16:07:20,538 INFO sqlalchemy.engine.Engine SELECT `ProdottiOrdinati`.`ID` AS `ProdottoOrdinatoID`, `ProdottiOrdinati`.`NumeroOrdine` AS `ProdottiOrdinati_NumeroOrdine`, `ProdottiOrdinati`.`NomeModello` AS `ProdottiOrdinati_NomeModello`, `ProdottiOrdinati`.`Quantita` AS `ProdottiOrdinati_Quantita`, `ProdottiOrdinati`.`PrezzoUnitario` AS `PrezzoUnitarioProdotto`, `ProdottiOrdinati`.`Valuta` AS `ValutaProdotto`, `ProdottiOrdinati`.`DataAggiunta` AS `ProdottiOrdinati_DataAggiunta`, `ProdottiOrdinati`.`DataConsegnaPrevista` AS `ProdottiOrdinati_DataConsegnaPrevista`, `ProdottiOrdinati`.`StatoProdotto` AS `ProdottiOrdinati_StatoProdotto`, `ProdottiOrdinati`.`NumeroRMA` AS `ProdottiOrdinati_NumeroRMA`, `ProdottiOrdinati`.`Note` AS `NoteProdotto`, `ApparecchiatureElettroniche`.`NomeModello` AS `NomeModelloApparecchiatura`, `ApparecchiatureElettroniche`.`NumeroSerie` AS `ApparecchiatureElettroniche_NumeroSerie`, `ApparecchiatureElettroniche`.`DataProduzione` AS `ApparecchiatureElettroniche_DataProduzione`, `ApparecchiatureElettroniche`.`Reparto` AS `ApparecchiatureElettroniche_Reparto`, `ApparecchiatureElettroniche`.`Fornitore` AS `FornitoreApparecchiatura`, `ApparecchiatureElettroniche`.`DataAcquisto` AS `ApparecchiatureElettroniche_DataAcquisto`, `ApparecchiatureElettroniche`.`Cliente` AS `ApparecchiatureElettroniche_Cliente`, `ApparecchiatureElettroniche`.`RepartoAssistenza` AS `ApparecchiatureElettroniche_RepartoAssistenza`, `ApparecchiatureElettroniche`.`DataUltimaManutenzione` AS `ApparecchiatureElettroniche_DataUltimaManutenzione`, `ApparecchiatureElettroniche`.`GaranziaScadenza` AS `ApparecchiatureElettroniche_GaranziaScadenza`, `ApparecchiatureElettroniche`.`DescrizioneProblema` AS `ApparecchiatureElettroniche_DescrizioneProblema`, `ApparecchiatureElettroniche`.`ComponenteDifettoso` AS `ApparecchiatureElettroniche_ComponenteDifettoso`, `ApparecchiatureElettroniche`.`TecnicoAssistenza` AS `ApparecchiatureElettroniche_TecnicoAssistenza`, `ApparecchiatureElettroniche`.`Note` AS `NoteApparecchiatura`, `OrdiniClienti`.`NumeroOrdine` AS `NumeroOrdineCliente`, `OrdiniClienti`.`DataOrdine` AS `OrdiniClienti_DataOrdine`, `OrdiniClienti`.`Cliente` AS `ClienteOrdine`, `OrdiniClienti`.`IndirizzoSpedizione` AS `OrdiniClienti_IndirizzoSpedizione`, `OrdiniClienti`.`CittaSpedizione` AS `OrdiniClienti_CittaSpedizione`, `OrdiniClienti`.`CAPSpedizione` AS `OrdiniClienti_CAPSpedizione`, `OrdiniClienti`.`ProvinciaSpedizione` AS `OrdiniClienti_ProvinciaSpedizione`, `OrdiniClienti`.`NazioneSpedizione` AS `OrdiniClienti_NazioneSpedizione`, `OrdiniClienti`.`MetodoPagamento` AS `OrdiniClienti_MetodoPagamento`, `OrdiniClienti`.`StatoPagamento` AS `OrdiniClienti_StatoPagamento`, `OrdiniClienti`.`DataPagamento` AS `OrdiniClienti_DataPagamento`, `OrdiniClienti`.`MetodoSpedizione` AS `OrdiniClienti_MetodoSpedizione`, `OrdiniClienti`.`DataSpedizione` AS `OrdiniClienti_DataSpedizione`, `OrdiniClienti`.`StatoSpedizione` AS `OrdiniClienti_StatoSpedizione`, `OrdiniClienti`.`DataConsegna` AS `OrdiniClienti_DataConsegna`, `OrdiniClienti`.`TotaleOrdine` AS `OrdiniClienti_TotaleOrdine`, `OrdiniClienti`.`Valuta` AS `ValutaOrdine`, `OrdiniClienti`.`NumeroFattura` AS `OrdiniClienti_NumeroFattura`, `OrdiniClienti`.`CodicePromozionale` AS `OrdiniClienti_CodicePromozionale`, `OrdiniClienti`.`Note` AS `NoteOrdine`
FROM `ProdottiOrdinati` INNER JOIN `ApparecchiatureElettroniche` ON `ProdottiOrdinati`.`NomeModello` = `ApparecchiatureElettroniche`.`NomeModello` INNER JOIN `OrdiniClienti` ON `ProdottiOrdinati`.`NumeroOrdine` = `OrdiniClienti`.`NumeroOrdine`
WHERE `ProdottiOrdinati`.`DataAggiunta` BETWEEN %s AND %s AND `ApparecchiatureElettroniche`.`DataProduzione` <= %s AND `OrdiniClienti`.`DataOrdine` >= %s
2023-11-13 16:07:20,538 INFO sqlalchemy.engine.Engine [generated in 0.00101s] ('2022-01-01', '2023-06-30', '2023-06-30', '2022-01-01')
(15, 19, 'popular', 2, Decimal('636.16'), 'EUR', datetime.date(2022, 5, 5), datetime.date(2022, 12, 9), 'In attesa di spedizione', 'RMA9114', 'Situation once treatment fact. Game big stage never turn every never. Person man another control picture industry professional. Realize effect dark.\nRelationship floor join past skin you cold.', 'popular', 'SN029', datetime.date(2016, 9, 29), 'government', 'Jensen LLC', datetime.date(2020, 10, 2), 'Nguyen PLC', 'school', datetime.date(2021, 3, 18), datetime.date(2022, 12, 2), 'Population apply create speak determine entire. Very now foot hard information material suggest.\nMission scientist knowledge total. Organization individual early.', 'tonight', 'Kevin Stewart', 'Agency operation wide ball. Late something cause door something. Various score final expect full.\nStructure national deep specific network. Old make under free military fish top item.', 19, datetime.date(2022, 2, 28), 'Guerrero and Sons', '4127 Perry Neck\nEast Andrew, HI 81161', 'South Garyfurt', '46406', 'AL', 'Guinea-Bissau', 'Bonifico bancario', 'Completato', datetime.date(2022, 9, 15), 'Posta prioritaria', datetime.date(2022, 12, 25), 'In preparazione', datetime.date(2022, 12, 28), Decimal('651.26'), 'EUR', 'INV9006', 'PROMO5', 'Send boy wide figure use still. Determine film position never. Market within several ok.')
(17, 38, 'anyone', 4, Decimal('178.20'), 'EUR', datetime.date(2022, 1, 9), datetime.date(2022, 11, 29), 'Spedito', 'RMA5567', 'Stage impact reality nature she. Listen seek guy most. Address so including each high.\nDefense certainly five citizen get resource economy.', 'anyone', 'SN021', datetime.date(2021, 6, 3), 'his', 'Fitzgerald, Kelly and Larson', datetime.date(2022, 10, 24), 'Douglas, Smith and Mack', 'increase', datetime.date(2022, 12, 1), datetime.date(2022, 12, 24), 'Scene success throughout chance recent. Half about phone respond really two make. Change former worry thought leg.', 'Democrat', 'Rebecca Rodriguez', 'Until yourself forward room. Product issue avoid. Design morning anything four beyond.\nTogether civil daughter partner name. Task American across. Nation herself fish finish.', 38, datetime.date(2022, 5, 24), 'Wilson Ltd', '400 Joe Mountain\nMccannmouth, CT 71721', 'Jacobsonmouth', '05082', 'MO', 'Armenia', 'Bonifico bancario', 'Completato', datetime.date(2022, 9, 8), 'Corriere espresso', datetime.date(2022, 12, 15), 'In preparazione', datetime.date(2022, 12, 23), Decimal('971.59'), 'USD', 'INV2474', 'PROMO5', 'Arrive trouble city little western party. Fish sort culture skin travel democratic. Red defense down difference issue. Dark admit eight friend best.')
(17, 38, 'anyone', 4, Decimal('178.20'), 'EUR', datetime.date(2022, 1, 9), datetime.date(2022, 11, 29), 'Spedito', 'RMA5567', 'Stage impact reality nature she. Listen seek guy most. Address so including each high.\nDefense certainly five citizen get resource economy.', 'anyone', 'SN035', datetime.date(2019, 7, 16), 'despite', 'Smith Group', datetime.date(2022, 1, 17), 'Ramirez-Jones', 'popular', datetime.date(2022, 7, 15), datetime.date(2022, 9, 28), 'Begin approach she increase station level. Machine list baby traditional term. Again white thing suggest it commercial.', 'follow', 'Julia Lopez', 'Without back view staff foot worker return. Operation population action memory role single determine.', 38, datetime.date(2022, 5, 24), 'Wilson Ltd', '400 Joe Mountain\nMccannmouth, CT 71721', 'Jacobsonmouth', '05082', 'MO', 'Armenia', 'Bonifico bancario', 'Completato', datetime.date(2022, 9, 8), 'Corriere espresso', datetime.date(2022, 12, 15), 'In preparazione', datetime.date(2022, 12, 23), Decimal('971.59'), 'USD', 'INV2474', 'PROMO5', 'Arrive trouble city little western party. Fish sort culture skin travel democratic. Red defense down difference issue. Dark admit eight friend best.')
2023-11-13 16:07:20,538 INFO sqlalchemy.engine.Engine ROLLBACK
2023-11-13 16:07:20,546 INFO sqlalchemy.engine.Engine SELECT DATABASE()
2023-11-13 16:07:20,546 INFO sqlalchemy.engine.Engine [raw sql] ()
2023-11-13 16:07:20,546 INFO sqlalchemy.engine.Engine SELECT @@sql_mode
2023-11-13 16:07:20,554 INFO sqlalchemy.engine.Engine [raw sql] ()
2023-11-13 16:07:20,554 INFO sqlalchemy.engine.Engine SELECT @@lower_case_table_names
2023-11-13 16:07:20,554 INFO sqlalchemy.engine.Engine [raw sql] ()
2023-11-13 16:07:20,554 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-11-13 16:07:20,554 INFO sqlalchemy.engine.Engine DESCRIBE `database4test`.`ProdottiOrdinati`
2023-11-13 16:07:20,559 INFO sqlalchemy.engine.Engine [raw sql] ()
2023-11-13 16:07:20,559 INFO sqlalchemy.engine.Engine DESCRIBE `database4test`.`ApparecchiatureElettroniche`
2023-11-13 16:07:20,563 INFO sqlalchemy.engine.Engine [raw sql] ()
2023-11-13 16:07:20,563 INFO sqlalchemy.engine.Engine DESCRIBE `database4test`.`OrdiniClienti`
2023-11-13 16:07:20,563 INFO sqlalchemy.engine.Engine [raw sql] ()
2023-11-13 16:07:20,570 INFO sqlalchemy.engine.Engine COMMIT
2023-11-13 16:07:20,570 INFO sqlalchemy.engine.Engine BEGIN (implicit)